name: Check with latest Rzk

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
  # and pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check formalisations
    steps:
      - uses: actions/checkout@v3

      - name: Check all files
        uses: rzk-lang/rzk-action@v1
        with:
          rzk-version: latest
          files: |
            src/1-foundations/1-type-theory/*.rzk.md
            src/1-foundations/1-type-theory/exercises/*.rzk.md
            src/1-foundations/2-homotopy-type-theory/*.rzk.md
            src/1-foundations/2-homotopy-type-theory/exercises/*.rzk.md
